app/mods/views.py
from flask import Blueprint, send_from_directory, abort, render_template, request, flash, redirect, url_for,\
    current_app
from app import db, workshopzips
from flask.ext.uploads import UploadNotAllowed
from flask.ext.login import current_user, login_required
from ..utils.utils import extract_and_image, package_mod_to_item
from ..tf2.models import TF2Item, TF2BodyGroup, TF2EquipRegion, TF2Class
from ..tf2.views import format_query, item_search
from ..tf2.functions import sort_classes, sort_classes_search
from ..users.models import User
from ..users.functions import new_user
from models import Mod, ModPackage, PackageDownload, ModImage, ModAuthor, Tag, ModClassModel
from forms import ItemSearch, EditMod, ModSearch
from functions import check_mod_permissions, check_edit_permissions, get_mod_stats, enabled_mods
from ..functions import remove_duplicates
from sqlalchemy import func, or_, and_
import datetime
import os
import json

mods = Blueprint("mods", __name__, url_prefix="/mods")


@mods.route('/')
@mods.route('/page/<int:page>/')
def all_mods(page=1):
    return search(page=page, all_mods=True)


@mods.route('/tag/<string:tag_id>/')
def tag(tag_id=None):
    tag_info = Tag.query.get(tag_id)
    if not tag_info:
        return abort(404)
    mods = enabled_mods().filter(Mod.tags.any(Tag.id == tag_id)).limit(18).all()
    for mod in mods:
        mod_stats = get_mod_stats(mod)
    return render_template('mods/tag.html', mods=mods, tag_info=tag_info, bg_num=tag_info.bg_num,
                           tag_theme=tag_info.id if tag_info.css else None,
                           title=tag_info.id.capitalize() + " tagged mods")
    #return render_template('construction.html', bg_num=tag_info.bg_num,
                           #title=tag_info.id.capitalize() + " tagged mods - Under construction")


@mods.route('/<int:mod_id>/')
@mods.route('/<int:mod_id>/page/<int:page>/')
def page(mod_id, page=1):
    mod = Mod.query.get_or_404(mod_id)
    check_mod_permissions(mod)
    mod_stats = get_mod_stats(mod, True)

    item_results = format_query(mod_stats.get("item_query"), mod.id, page)

    item_search_form = ItemSearch()

    classes = mod.class_model
    sorted_classes = sort_classes(classes)

    item_search_form.equip_regions.query = TF2EquipRegion.query.all()
    item_search_form.bodygroups.query = TF2BodyGroup.query.all()
    item_search_form.classes.choices = sorted_classes

    item_search_form.classes.data = [_class for _class in classes]
    item_search_form.bodygroups.data = [bodygroup for bodygroup in mod.bodygroups]
    item_search_form.equip_regions.data = [equip_region for equip_region in mod.equip_regions]

    return render_template('mods/page.html', mod=mod, mod_stats=mod_stats, item_search=item_search_form, mod_id=mod.id,
                           item_results=item_results.get('items'), page=page, title=mod.pretty_name,
                           sorted_classes=sorted_classes)


@mods.route('/<int:mod_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(mod_id):
    mod = Mod.query.get_or_404(mod_id)
    new_item = False
    if request.referrer == url_for(".upload", _external=True):
        new_item = True

    check_edit_permissions(mod)
    edit_form = EditMod()

    edit_form.equip_regions.query = TF2EquipRegion.query.all()
    edit_form.bodygroups.query = TF2BodyGroup.query.all()
    edit_form.tags.query = Tag.query.all()

    package_formats = [("vpk", "VPK")]
    visibilities = [("Pu", "Public"), ("Pr", "Unlisted"), ("H", "Hidden")]

    edit_form.package_format.choices = package_formats
    edit_form.visibility.choices = visibilities

    if edit_form.workshop_id.data == "":
        edit_form.workshop_id.data = None

    if edit_form.validate_on_submit():
        valid = True
        mod.pretty_name = edit_form.pretty_name.data
        mod.description = edit_form.description.data
        workshop_id = edit_form.workshop_id.data
        if workshop_id:
            from re import match
            try:
                if match("http[s]?:\/\/(www\.)?steamcommunity\.com\/sharedfiles\/filedetails\/", workshop_id):
                    from urlparse import urlparse, parse_qs
                    workshop_id = parse_qs(urlparse(workshop_id).query).get("id")[0]
                    int(workshop_id)
                elif not int(workshop_id) > 0:
                    valid = False
                    edit_form.workshop_id.errors.append("Not a valid workshop ID.")
                    workshop_id = None
            except (ValueError, TypeError):
                valid = False
                edit_form.workshop_id.errors.append("Not a valid workshop ID.")
                workshop_id = None
            mod.workshop_id = workshop_id
        if not workshop_id or workshop_id == "":
            mod.workshop_id = None

        mod.package_format = edit_form.package_format.data
        mod.visibility = edit_form.visibility.data

        mod.defindex = edit_form.defindex.data
        if not mod.defindex.isnumeric():
            mod.defindex = None

        mod.hide_downloads = edit_form.hide_downloads.data

        if mod.hide_downloads and not mod.defindex:
            mod.hide_downloads = False
            flash("If the item is not officially in-game, please simply change the item visibility to hidden to remove downloads.", "danger")

        mod.bodygroups = []
        mod.equip_regions = []

        for bodygroup in edit_form.bodygroups.data:
            mod.bodygroups.append(TF2BodyGroup.query.get(bodygroup))

        for equip_region in edit_form.equip_regions.data:
            mod.equip_regions.append(TF2EquipRegion.query.get(equip_region))

        for tag in edit_form.tags.data:
            mod.tags.append(Tag.query.get(tag))

        authors_to_add = []
        for i, author in enumerate(edit_form.authors):
            authors_to_add.append((i, author.author.data))

        author_profiles = []
        for i, add_author in authors_to_add:
            if add_author:
                user_author_record = new_user(add_author)

                if isinstance(user_author_record, str):
                    edit_form.authors.entries[i].author.errors.append(user_author_record)
                    valid = False
                else:
                    author_profiles.append(user_author_record)

        if not current_user.is_admin() and current_user not in author_profiles:
            edit_form.authors.errors.append("You may not remove yourself as an author.")
            valid = False

        author_profiles = remove_duplicates(author_profiles)

        if valid:
            for i in range(0, len(mod.authors)):
                mod.authors.pop()
            for i, author_profile in enumerate(author_profiles):
                mod_author = ModAuthor(mod_id=mod.id, user_id=author_profile.account_id, order=i)
                db.session.add(mod_author)
            db.session.add(mod)
            db.session.commit()
            flash("Save successful.", "success")
            return redirect(url_for("mods.page", mod_id=mod.id))

    classes = [_class for _class in mod.class_model]

    edit_form.pretty_name.data = mod.pretty_name
    edit_form.workshop_id.data = mod.workshop_id
    edit_form.description.data = mod.description
    for i, author in enumerate(mod.authors):
        edit_form.authors[i].author.data = author.perma_profile_url
    edit_form.equip_regions.data = [equip_region for equip_region in mod.equip_regions]
    edit_form.bodygroups.data = [bodygroup for bodygroup in mod.bodygroups]
    edit_form.tags.data = [tag for tag in mod.tags]
    edit_form.package_format.data = mod.package_format
    edit_form.visibility.data = mod.visibility
    edit_form.hide_downloads.data = mod.hide_downloads
    edit_form.defindex.data = mod.defindex
    if new_item:
        edit_form.visibility.data = "Pu"
        edit_form.publish.label.text += " and Publish!"

    classes_array = json.dumps(classes)

    count = item_search(
        classes=classes,
        bodygroups=[bodygroup.bodygroup for bodygroup in mod.bodygroups],
        equip_regions=[equip_region.equip_region for equip_region in mod.equip_regions]
    ).count()

    """if request.method == 'POST' and 'mod_image' in request.files:
        try:
            filename = modimages.save(request.files['mod_image'])
            print filename
        except UploadNotAllowed:
            flash("Only images can be uploaded.", "danger")
        <form method=POST enctype=multipart/form-data>
            <input type=file name=mod_image>
            <input type="submit" value="Submit">
        </form>"""
    return render_template('mods/edit.html', mod=mod, edit_form=edit_form, classes=classes_array, count=count,
                           title=u"Editing {}".format(mod.pretty_name))


@mods.route('/search/')
@mods.route('/search/page/<int:page>/')
def search(page=1, all_mods=False):

    _mods = None

    mod_search = ModSearch()

    mod_search.equip_regions.query = TF2EquipRegion.query.all()
    mod_search.bodygroups.query = TF2BodyGroup.query.all()
    mod_search.classes.choices = sort_classes_search(TF2Class.query.all())
    mod_search.tags.query = Tag.query.all()

    search_submitted = any([all_mods, request.args])

    if search_submitted:
        item_name = request.args.get('item_name')
        equip_regions = request.args.getlist('equip_regions')
        bodygroups = request.args.getlist('bodygroups')
        classes = request.args.getlist('classes')
        tags = request.args.getlist('tags')

        mod_search.item_name.data = item_name
        mod_search.equip_regions.data = equip_regions
        mod_search.bodygroups.data = bodygroups
        mod_search.classes.data = classes
        mod_search.tags.data = tags

        _mods = enabled_mods()
        wildcards = ["%", "_"]
        if item_name:
            if any([w in item_name for w in wildcards]):
                return
            _mods = _mods.filter(Mod.pretty_name.contains(item_name))

app/tf2/views.py
from flask import url_for, Response, abort, Blueprint, request, render_template
from models import TF2Item, TF2ClassModel, TF2BodyGroup, TF2EquipRegion, schema_bodygroup
from ..mods.models import Mod, PackageDownload, ModPackage
from flask.ext.login import login_required
from sqlalchemy import func, or_, and_
import json
from .. import db
from sqlalchemy import desc

tf2 = Blueprint("tf2", __name__, url_prefix="/tf2")


def item_search(classes=None, bodygroups=None, equip_regions=None, item_name=None):
    items_query = TF2Item.query.filter_by(inactive=False)
    wildcards = ["%", "_"]
    if item_name:
        if any([w in item_name for w in wildcards]):
            return
        items_query = items_query.filter(TF2Item.item_name.contains(item_name))
    if len(classes) > 0:
        for class_name in classes:
            items_query = items_query.filter(TF2Item.class_model.any(TF2ClassModel.class_name == class_name))
        sq = db.session.query(TF2ClassModel.defindex, func.count(TF2ClassModel).label("class_count")).group_by(TF2ClassModel.defindex).subquery()
        items_query = items_query.join(sq, TF2Item.defindex == sq.c.defindex)
        if len(classes) == 9:
            pass
        elif len(classes) > 1:
            items_query = items_query.filter(sq.c.class_count > 1).filter(sq.c.class_count < 9)
        elif len(classes) == 1:
            items_query = items_query.filter(sq.c.class_count == 1)
    else:
        return
    if equip_regions:
        items_query = items_query.filter(TF2Item.equip_regions.any(or_(*[TF2EquipRegion.equip_region == equip_region for equip_region in equip_regions])))
    if bodygroups:
        items_query = items_query.filter(TF2Item.bodygroups.any(or_(*[TF2BodyGroup.bodygroup == bodygroup for bodygroup in bodygroups])))
        bodygroup_count = db.session.query(schema_bodygroup.c.defindex, func.count('*').label("bg_count")).group_by(schema_bodygroup.c.defindex).subquery()
        items_query = items_query.join(bodygroup_count, TF2Item.defindex == bodygroup_count.c.defindex).filter(bodygroup_count.c.bg_count == len(bodygroups))
    return items_query


def format_query(items_query, mod_id, page):
    mod = Mod.query.get_or_404(mod_id)
    authors = set(user.account_id for user in mod.authors)
    if items_query and items_query.count() > 0:
        count = items_query.count()
        items_query = items_query.paginate(int(page), per_page=36)
        for item in items_query.items:
            item.downloads = PackageDownload.query.join(ModPackage).join(TF2Item).filter(TF2Item.defindex == item.defindex) \
                .filter(ModPackage.mod_id == mod_id).filter(~PackageDownload.user_id.in_(authors)).count()
    else:
        return {"err_msg": "No items found matching these criteria.", "count": 0}

    items = render_template('tf2/api_result.html', items=items_query, mod_id=mod_id)
    return {"items": items, "count": count}


@tf2.route('/api/', methods=['POST'])
@login_required
def api():
    form_values = request.form
    item_name = form_values.get("search_data[item_name]")
    classes = form_values.getlist("search_data[classes][]")
    bodygroups = form_values.getlist("search_data[bodygroups][]")
    equip_regions = form_values.getlist("search_data[equip_regions][]")
    mod_id = form_values.get("mod_id")
    page = form_values.get('page')
    if len(classes) < 1:
        return Response(json.dumps({"err_msg": "No classes selected, please select a class to search.", "count": 0}),  mimetype='application/json')
    if not page.isnumeric():
        return Response(json.dumps({"err_msg": "Error, please refresh the page and try again.", "count": 0}),  mimetype='application/json')

    items_query = item_search(classes, bodygroups, equip_regions, item_name)
    items_dict = format_query(items_query, mod_id, page)

    if "err_msg" in items_dict:
        return Response(json.dumps({"err_msg": items_dict.get('err_msg')}),  mimetype='application/json')

    return Response(json.dumps(items_dict),  mimetype='application/json')


@tf2.route('/api/count/', methods=['POST'])
@login_required
def api_count():
    form_values = request.form
    item_name = form_values.get("search_data[item_name]")
    classes = form_values.getlist("search_data[classes][]")
    bodygroups = form_values.getlist("search_data[bodygroups][]")
    equip_regions = form_values.getlist("search_data[equip_regions][]")
    page = request.form.get('page')
    if len(classes) < 1:
        return Response(json.dumps({"err_msg": "No classes selected, please select a class to search.", "count": 0}),  mimetype='application/json')
    if not page.isnumeric():
        return Response(json.dumps({"err_msg": "Error, please refresh the page and try again.", "count": 0}),  mimetype='application/json')

    items_query = item_search(classes, bodygroups, equip_regions, item_name)
    items_dict = {"count": items_query.count()}

    return Response(json.dumps(items_dict),  mimetype='application/json')


@tf2.route('/items/')
def item_download_counts():
    sq = db.session.query(ModPackage.defindex, func.count(PackageDownload).label("download_count"))\
        .join(PackageDownload).group_by(ModPackage.defindex).subquery()
    top_100_downloaded = db.session.query(TF2Item, "download_count").join(sq, TF2Item.defindex == sq.c.defindex)\
        .order_by(desc("download_count")).limit(100).all()
    return render_template('tf2/top_100_downloads.html', items=top_100_downloaded, title="Top {} replaced items".format(len(top_100_downloaded)))

app/templates/mods/edit.html
{% extends "layout.html" %}
{% from "macros.html" import form_field, steam_block, field_errors %}
{% block scripts %}
    {{ super() }}
    {% assets "edit_js" %}
        <script src="{{ ASSET_URL }}"></script>
        <script>
            var tf2_api = "{{ url_for("tf2.api_count") }}";
            var classes = {{ classes | safe }};
        </script>
    {% endassets %}
{% endblock %}
{% block content %}
    Settings for {{ mod.pretty_name }}
    <form method=POST id="edit_form" >
        {{ edit_form.hidden_tag() }}
        {{ form_field(edit_form.pretty_name) }}
        {{ form_field(edit_form.workshop_id, placeholder="Paste a link to the item on the Steam Workshop.") }}
        {{ form_field(edit_form.description, rows=5) }}
        {{ form_field(edit_form.tags) }}
        <div class="form-row form-authors">
            {{ edit_form.authors.label }}
            <div class="input">
                {%- for author_field in edit_form.authors -%}
                    <div class="author-field cf">
                        {%- if mod.authors[loop.index0] -%}
                            <div class="author-block cf">{{ steam_block(mod.authors[loop.index0], no_link=True) }}</div>
                        {%- endif -%}
                        <div class="input">{{ author_field.author(placeholder="Paste a user's Steam profile URL (/id/<vanity> or /profiles/<number>)", class="input-default") }}</div>
                        {{ field_errors(author_field.author) }}
                    </div>
                {%- endfor -%}
                {{ field_errors(edit_form.authors) }}
            </div>
        </div>
        {{ form_field(edit_form.equip_regions) }}
        {{ form_field(edit_form.bodygroups) }}
        <div class="form-row offset" id="item-count">The current settings return <span>{{ count | default(0) }}</span> compatible items.</div>
        {{ form_field(edit_form.package_format) }}
        {{ form_field(edit_form.defindex) }}
        {{ form_field(edit_form.hide_downloads) }}
        {{ form_field(edit_form.visibility) }}
        <div class="form-row offset">{{ edit_form.publish(class="input-default") }}</div>
    </form>
    <a href="{{ url_for('mods.page', mod_id=mod.id) }}">Return to the '{{ mod.pretty_name }}' page</a>
{% endblock %}
{% block styles %}
    {% assets "multiple-select" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {{ super() }}
{% endblock %}

app/templates/mods/macros.html
{% from "macros.html" import steam_block, mod_class, pagination %}
{%- macro mod_block(mod, large) -%}
    <a href="{{ url_for('mods.page', mod_id=mod.id) }}" class="mod{{ " large" if large }}">
        {{ mod_class("multi-class" if mod.class_model | length > 1 else mod.class_model.itervalues().next().class_name) }}
        <div class="info">
            <div class="authors">
                {%- for author in mod.authors -%}
                    {{ author.name }}{{ ", " if not loop.last }}
                {%- endfor -%}
            </div>
            <div class="name">{{ mod.pretty_name }}</div>
            <div class="spacer"></div>
            <div class="stats">
            <ul>
                <li>{{ mod.downloads | default(0) | format_thousands}}<span>Downloads</span></li>
                <li>{{ mod.replacements | default(0) | format_thousands }}+<span>Replacements</span></li>
            </ul>
            </div>
        </div>
        <img src="{{ url_for('mods.image', mod_id=mod.id, type=0) }}" />
    </a>
{%- endmacro -%}
{%- macro author_list(authors) -%}
    {%- for author in authors -%}
        {{ steam_block(author) }}
    {%- endfor -%}
{%- endmacro -%}
{%- macro readable_visibility(visibility) -%}
    {%- if visibility == "H" -%}
        Hidden
    {%- elif visibility == "Pu" -%}
        Public
    {%- elif visibility == "Pr" -%}
        Unlisted
    {%- else -%}
        Unknown
    {%- endif -%}
{%- endmacro -%}
{%- macro mod_table(mods, endpoint, endpoint_values={}) -%}
    {%- if mods.items | count > 0 -%}
    {{ pagination(mods, endpoint, endpoint_values) }}
    <table class="all_mod">
        <thead>
            <tr>
                <th>Mod</th>
                <th>Class</th>
                <th>Authors</th>
                <th>Downloads</th>
                <th>Replacements</th>
            </tr>
        </thead>
        <tbody>
            {%- for mod in mods.items -%}
                <tr>
                    <td><a class="small_item" href="{{ url_for('mods.page', mod_id=mod.id) }}"><div class="backpack_image"><img src="{{ url_for('mods.image', mod_id=mod.id, type=1) }}" /></div> {{ mod.pretty_name }}</a></td>
                    <td>{{ mod_class("multi-class" if mod.class_model | length > 1 else mod.class_model.itervalues().next().class_name) }}</td>
                    <td>
                        <div class="authors cf">
                            {%- for author in mod.authors -%}
                                <a class="iconholder" title="{{ author.name }}" href="{{ url_for('users.user_page', user_id=author.account_id) }}">
                                    <img src="{{ author.avatar_small }}"/>
                                </a>
                            {%- endfor -%}
                        </div>
                    </td>
                    <td>{{ mod.downloads | default(0) | format_thousands}}</td>
                    <td>{{ mod.replacements | default(0) | format_thousands}}+</td>
                </tr>
            {%- endfor -%}
        </tbody>
    </table>
    {{ pagination(mods, endpoint, endpoint_values) }}
    {%- else -%}
    No items found
    {%- endif -%}
{%- endmacro -%}
{%- macro mod_class(class_name) -%}
    <div class="mod_class {{ class_name }}" title="{{ class_name | capitalize }}"></div>
{%- endmacro -%}

app/templates/mods/page.html
{% extends "layout.html" %}
{% from "mods/macros.html" import author_list, readable_visibility %}
{% from 'macros.html' import wiki_link %}
{% if mod.class_model | length > 1 %}
    {% set mod_class = "multi-class" %}
{% else %}
    {% set mod_class = mod.class_model.itervalues().next().class_name %}
{% endif %}
{% block scripts %}
    {{ super() }}
    <script>
        var tf2_api = "{{ url_for("tf2.api") }}";
        var mod_id  = {{ mod_id }};
        var page = {{ page }};
    </script>
    {% assets "download_js" %}
        <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block content %}
    <div id="sidebar" class="cf">
        <div class="sidebar left">
            <div class="backpack_image">
                <img src="{{ url_for('.image', mod_id=mod.id, type=0) }}" />
            </div>
            <div class="mod-name">{{ mod.pretty_name }}</div>
        </div>
        <div class="sidebar right">
            <div class="authors cf">
                <span class="mod-stat-title">An item created by:</span>
                {{ author_list(mod.authors) }}
            </div>
            {%- if mod.workshop_id -%}
                <div class="workshop">
                    <a href="//steamcommunity.com/sharedfiles/filedetails/?id={{ mod.workshop_id }}" target="_blank" title="View on Steam Workshop"><img src="{{ url_for('static', filename='images/workshop.png') }}"/></a>
                </div>
            {%- endif -%}
            {%- if mod.defindex -%}
                {{ wiki_link(mod.defindex) }}
            {%- endif -%}
            <div>
                <span class="mod-stat-title">Downloads: </span>
                <span class="mod-stat">{{ mod_stats.downloads | default(0) | format_thousands}}</span>
            </div>
            <div>
                <span class="mod-stat-title">Replacements: </span>
                <span class="mod-stat">{{ mod_stats.replacements | default(0) | format_thousands }}+</span>
            </div>
            <div><span class="mod-stat-title">Class: </span>
                {%- for key, class in sorted_classes -%}
                    <a href="{{ url_for('.search', classes=class) }}">{{ class }}</a>{{ ", " if not loop.last }}
                {%- endfor -%}
            </div>
            {%- if mod.bodygroups | length > 0 -%}
                <div class="bodygroups">
                    <span class="mod-stat-title">Bodygroups: </span>
                    {%- for bodygroup in mod.bodygroups -%}
                        <a href="{{ url_for('.search', bodygroups=bodygroup.bodygroup) }}">{{ bodygroup }}</a>{{ ", " if not loop.last }}
                    {%- endfor -%}
                </div>
            {%- endif -%}
            <div class="equip_regions">
                <span class="mod-stat-title">Equip regions: </span>
                {%- if mod.equip_regions -%}
                {%- for equip_region in mod.equip_regions -%}
                    <a href="{{ url_for('.search', equip_regions=equip_region.equip_region) }}">{{ equip_region }}</a>{{ ", " if not loop.last }}
                {%- endfor -%}
                {%- else -%}
                    Any
                {%- endif -%}
            </div>
            {%- if mod.tags | length > 0 -%}
            <div class="equip_regions">
                <span class="mod-stat-title">Tags: </span>
                {%- for tag in mod.tags -%}
                    <a href="{{ url_for('.tag', tag_id=tag.id) }}">{{ tag }}</a>{{ ", " if not loop.last }}
                {%- endfor -%}
            </div>
            {%- endif -%}
            <div>
                <span class="mod-stat-title">Uploaded: </span>
                <span>{{ mod.uploaded | datetime_to_datestring }}</span>
            </div>
            {%- if current_user in mod.authors or current_user.is_admin() -%}
                <div id="owner_controls">
                    <div class="mod-stat-title">Owner controls</div>
                    <div><span class="mod-stat-title">Visibility:</span> {{ readable_visibility(mod.visibility) }}</div>
                    <div>
                        <span class="mod-stat-title">Downloads by authors: </span>
                        {{ mod_stats.author_downloads | default(0) | format_thousands}}
                    </div>
                    <div><a href="{{ url_for(".edit", mod_id=mod.id) }}">Edit mod</a></div>
                </div>
            {%- endif -%}
        </div>
    </div>
    <div class="mod-left">
        {%- if mod.description -%}
            <div class="mod-description">
                {{ mod.description | markdown }}
            </div>
        {%- endif -%}
        {%- if not mod.hide_downloads -%}
        {%- if current_user.is_authenticated() -%}
            <div class="item-search">
                <span>Filter for items to replace:</span>
                <form id="item_search" method="POST">
                    {{ item_search.hidden_tag() }}
                    {{ item_search.item_name(placeholder="Item name...", class="input-default") }}
                    {{ item_search.classes }}
                    {{ item_search.equip_regions }}
                    {{ item_search.bodygroups }}
                </form>
                <div id="results">
                    {%- if item_results -%}
                        {{ item_results | safe }}
                    {%- else -%}
                        No items found matching this criteria. Change the criteria above to find items.
                    {%- endif -%}
                </div>
            </div>
        {%- else -%}
            <div><a href="{{ url_for("users.login") }}"><img src="{{ url_for('static', filename='images/sits_small.png') }}"/></a> to repackage and download this mod.</div>
        {%- endif -%}
        {%- else -%}
            This mod is no longer available to download due to being available officially in-game!
            {% if mod.defindex %}Please see the <a href="http://wiki.teamfortress.com/scripts/itemredirect.php?id={{ mod.defindex }}" target="_blank" title="View on Official Team Fortress Wiki">Wiki page</a> for more information upon the item.{% endif %}
        {%- endif -%}
    </div>
{% endblock %}
{% block styles %}
    {% assets "multiple-select" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {{ super() }}
{% endblock %}

app/templates/mods/search.html
{% extends "layout.html" %}
{%- from 'mods/macros.html' import mod_table -%}
{% block scripts %}
    {{ super() }}
    {% assets "search_js" %}
        <script src="{{ ASSET_URL }}"></script>
    {% endassets %}
{% endblock %}
{% block content %}
    <form id="mod_search" method="GET" action="{{ url_for('mods.search') }}">
        {{ mod_search.item_name(placeholder="Item name...", class="input-default") }}
        {{ mod_search.classes(class="input-default") }}
        {{ mod_search.submit(class="input-default") }}
    </form>
    {%- if searched -%}
        {{ mod_table(mods, endpoint=request.endpoint, endpoint_values=request.args) }}
    {%- endif -%}
{% endblock %}
{% block styles %}
    {% assets "multiple-select" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet">
    {% endassets %}
    {{ super() }}
{% endblock %}

app/templates/mods/tag.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ tag_info.id | capitalize }} tagged mods</h1>
    {%- from 'macros.html' import mod_wall -%}
    {{ mod_wall(mods) }}
    {%- if mods | length > 9 -%}<div class="button_block"><a href="{{ url_for('mods.search', tags=tag_info.id) }}">View more...</a></div>{%- endif -%}
{% endblock %}

app/templates/mods/upload.html
{% extends "layout.html" %}
{% block content %}
    <form method=POST enctype=multipart/form-data class="upload-form">
        <div id="file-picker">
            <span>Browse for a <span class="gold_star">gold star</span> zip</span>
            <input type=file name=workshop_zip>
        </div>
        <input class="input-default" type="submit" value="Upload">
    </form>
{% endblock %}