app/mods/views.py
from flask import Blueprint, send_from_directory, abort, render_template, request, flash, redirect, url_for,\
    current_app
from app import db, workshopzips
from flask.ext.uploads import UploadNotAllowed
from flask.ext.login import current_user, login_required
from ..utils.utils import extract_and_image, package_mod_to_item
from ..tf2.models import TF2Item, TF2BodyGroup, TF2EquipRegion, TF2Class
from ..tf2.views import format_query, item_search
from ..tf2.functions import sort_classes, sort_classes_search
from ..users.models import User
from ..users.functions import new_user
from models import Mod, ModPackage, PackageDownload, ModImage, ModAuthor, Tag, ModClassModel
from forms import ItemSearch, EditMod, ModSearch
from functions import check_mod_permissions, check_edit_permissions, get_mod_stats, enabled_mods
from ..functions import remove_duplicates
from sqlalchemy import func, or_, and_
import datetime
import os
import json

mods = Blueprint("mods", __name__, url_prefix="/mods")


@mods.route('/')
@mods.route('/page/<int:page>/')
def all_mods(page=1):
    return search(page=page, all_mods=True)


@mods.route('/tag/<string:tag_id>/')
def tag(tag_id=None):
    tag_info = Tag.query.get(tag_id)
    if not tag_info:
        return abort(404)
    mods = enabled_mods().filter(Mod.tags.any(Tag.id == tag_id)).limit(18).all()
    for mod in mods:
        mod_stats = get_mod_stats(mod)
    return render_template('mods/tag.html', mods=mods, tag_info=tag_info, bg_num=tag_info.bg_num,
                           tag_theme=tag_info.id if tag_info.css else None,
                           title=tag_info.id.capitalize() + " tagged mods")
    #return render_template('construction.html', bg_num=tag_info.bg_num,
                           #title=tag_info.id.capitalize() + " tagged mods - Under construction")


@mods.route('/<int:mod_id>/')
@mods.route('/<int:mod_id>/page/<int:page>/')
def page(mod_id, page=1):
    mod = Mod.query.get_or_404(mod_id)
    check_mod_permissions(mod)
    mod_stats = get_mod_stats(mod, True)

    item_results = format_query(mod_stats.get("item_query"), mod.id, page)

    item_search_form = ItemSearch()

    classes = mod.class_model
    sorted_classes = sort_classes(classes)

    item_search_form.equip_regions.query = TF2EquipRegion.query.all()
    item_search_form.bodygroups.query = TF2BodyGroup.query.all()
    item_search_form.classes.choices = sorted_classes

    item_search_form.classes.data = [_class for _class in classes]
    item_search_form.bodygroups.data = [bodygroup for bodygroup in mod.bodygroups]
    item_search_form.equip_regions.data = [equip_region for equip_region in mod.equip_regions]

    return render_template('mods/page.html', mod=mod, mod_stats=mod_stats, item_search=item_search_form, mod_id=mod.id,
                           item_results=item_results.get('items'), page=page, title=mod.pretty_name,
                           sorted_classes=sorted_classes)


@mods.route('/<int:mod_id>/edit/', methods=['GET', 'POST'])
@login_required
def edit(mod_id):
    mod = Mod.query.get_or_404(mod_id)
    new_item = False
    if request.referrer == url_for(".upload", _external=True):
        new_item = True

    check_edit_permissions(mod)
    edit_form = EditMod()

    edit_form.equip_regions.query = TF2EquipRegion.query.all()
    edit_form.bodygroups.query = TF2BodyGroup.query.all()
    edit_form.tags.query = Tag.query.all()

    package_formats = [("vpk", "VPK")]
    visibilities = [("Pu", "Public"), ("Pr", "Unlisted"), ("H", "Hidden")]

    edit_form.package_format.choices = package_formats
    edit_form.visibility.choices = visibilities

    if edit_form.workshop_id.data == "":
        edit_form.workshop_id.data = None

    if edit_form.validate_on_submit():
        valid = True
        mod.pretty_name = edit_form.pretty_name.data
        mod.description = edit_form.description.data
        workshop_id = edit_form.workshop_id.data
        if workshop_id:
            from re import match
            try:
                if match("http[s]?:\/\/(www\.)?steamcommunity\.com\/sharedfiles\/filedetails\/", workshop_id):
                    from urlparse import urlparse, parse_qs
                    workshop_id = parse_qs(urlparse(workshop_id).query).get("id")[0]
                    int(workshop_id)
                elif not int(workshop_id) > 0:
                    valid = False
                    edit_form.workshop_id.errors.append("Not a valid workshop ID.")
                    workshop_id = None
            except (ValueError, TypeError):
                valid = False
                edit_form.workshop_id.errors.append("Not a valid workshop ID.")
                workshop_id = None
            mod.workshop_id = workshop_id
        if not workshop_id or workshop_id == "":
            mod.workshop_id = None

        mod.package_format = edit_form.package_format.data
        mod.visibility = edit_form.visibility.data

        mod.defindex = edit_form.defindex.data
        if not mod.defindex.isnumeric():
            mod.defindex = None

        mod.hide_downloads = edit_form.hide_downloads.data

        if mod.hide_downloads and not mod.defindex:
            mod.hide_downloads = False
            flash("If the item is not officially in-game, please simply change the item visibility to hidden to remove downloads.", "danger")

        mod.bodygroups = []
        mod.equip_regions = []

        for bodygroup in edit_form.bodygroups.data:
            mod.bodygroups.append(TF2BodyGroup.query.get(bodygroup))

        for equip_region in edit_form.equip_regions.data:
            mod.equip_regions.append(TF2EquipRegion.query.get(equip_region))

        for tag in edit_form.tags.data:
            mod.tags.append(Tag.query.get(tag))

        authors_to_add = []
        for i, author in enumerate(edit_form.authors):
            authors_to_add.append((i, author.author.data))

        author_profiles = []
        for i, add_author in authors_to_add:
            if add_author:
                user_author_record = new_user(add_author)

                if isinstance(user_author_record, str):
                    edit_form.authors.entries[i].author.errors.append(user_author_record)
                    valid = False
                else:
                    author_profiles.append(user_author_record)

        if not current_user.is_admin() and current_user not in author_profiles:
            edit_form.authors.errors.append("You may not remove yourself as an author.")
            valid = False

        author_profiles = remove_duplicates(author_profiles)

        if valid:
            for i in range(0, len(mod.authors)):
                mod.authors.pop()
            for i, author_profile in enumerate(author_profiles):
                mod_author = ModAuthor(mod_id=mod.id, user_id=author_profile.account_id, order=i)
                db.session.add(mod_author)
            db.session.add(mod)
            db.session.commit()
            flash("Save successful.", "success")
            return redirect(url_for("mods.page", mod_id=mod.id))

    classes = [_class for _class in mod.class_model]

    edit_form.pretty_name.data = mod.pretty_name
    edit_form.workshop_id.data = mod.workshop_id
    edit_form.description.data = mod.description
    for i, author in enumerate(mod.authors):
        edit_form.authors[i].author.data = author.perma_profile_url
    edit_form.equip_regions.data = [equip_region for equip_region in mod.equip_regions]
    edit_form.bodygroups.data = [bodygroup for bodygroup in mod.bodygroups]
    edit_form.tags.data = [tag for tag in mod.tags]
    edit_form.package_format.data = mod.package_format
    edit_form.visibility.data = mod.visibility
    edit_form.hide_downloads.data = mod.hide_downloads
    edit_form.defindex.data = mod.defindex
    if new_item:
        edit_form.visibility.data = "Pu"
        edit_form.publish.label.text += " and Publish!"

    classes_array = json.dumps(classes)

    count = item_search(
        classes=classes,
        bodygroups=[bodygroup.bodygroup for bodygroup in mod.bodygroups],
        equip_regions=[equip_region.equip_region for equip_region in mod.equip_regions]
    ).count()

    """if request.method == 'POST' and 'mod_image' in request.files:
        try:
            filename = modimages.save(request.files['mod_image'])
            print filename
        except UploadNotAllowed:
            flash("Only images can be uploaded.", "danger")
        <form method=POST enctype=multipart/form-data>
            <input type=file name=mod_image>
            <input type="submit" value="Submit">
        </form>"""
    return render_template('mods/edit.html', mod=mod, edit_form=edit_form, classes=classes_array, count=count,
                           title=u"Editing {}".format(mod.pretty_name))


@mods.route('/search/')
@mods.route('/search/page/<int:page>/')
def search(page=1, all_mods=False):

    _mods = None

    mod_search = ModSearch()

    mod_search.equip_regions.query = TF2EquipRegion.query.all()
    mod_search.bodygroups.query = TF2BodyGroup.query.all()
    mod_search.classes.choices = sort_classes_search(TF2Class.query.all())
    mod_search.tags.query = Tag.query.all()

    search_submitted = any([all_mods, request.args])

    if search_submitted:
        item_name = request.args.get('item_name')
        equip_regions = request.args.getlist('equip_regions')
        bodygroups = request.args.getlist('bodygroups')
        classes = request.args.getlist('classes')
        tags = request.args.getlist('tags')

        mod_search.item_name.data = item_name
        mod_search.equip_regions.data = equip_regions
        mod_search.bodygroups.data = bodygroups
        mod_search.classes.data = classes
        mod_search.tags.data = tags

        _mods = enabled_mods()
        wildcards = ["%", "_"]
        if item_name:
            if any([w in item_name for w in wildcards]):
                return
            _mods = _mods.filter(Mod.pretty_name.contains(item_name))

app/tf2/views.py
from flask import url_for, Response, abort, Blueprint, request, render_template
from models import TF2Item, TF2ClassModel, TF2BodyGroup, TF2EquipRegion, schema_bodygroup
from ..mods.models import Mod, PackageDownload, ModPackage
from flask.ext.login import login_required
from sqlalchemy import func, or_, and_
import json
from .. import db
from sqlalchemy import desc

tf2 = Blueprint("tf2", __name__, url_prefix="/tf2")


def item_search(classes=None, bodygroups=None, equip_regions=None, item_name=None):
    items_query = TF2Item.query.filter_by(inactive=False)
    wildcards = ["%", "_"]
    if item_name:
        if any([w in item_name for w in wildcards]):
            return
        items_query = items_query.filter(TF2Item.item_name.contains(item_name))
    if len(classes) > 0:
        for class_name in classes:
            items_query = items_query.filter(TF2Item.class_model.any(TF2ClassModel.class_name == class_name))
        sq = db.session.query(TF2ClassModel.defindex, func.count(TF2ClassModel).label("class_count")).group_by(TF2ClassModel.defindex).subquery()
        items_query = items_query.join(sq, TF2Item.defindex == sq.c.defindex)
        if len(classes) == 9:
            pass
        elif len(classes) > 1:
            items_query = items_query.filter(sq.c.class_count > 1).filter(sq.c.class_count < 9)
        elif len(classes) == 1:
            items_query = items_query.filter(sq.c.class_count == 1)
    else:
        return
    if equip_regions:
        items_query = items_query.filter(TF2Item.equip_regions.any(or_(*[TF2EquipRegion.equip_region == equip_region for equip_region in equip_regions])))
    if bodygroups:
        items_query = items_query.filter(TF2Item.bodygroups.any(or_(*[TF2BodyGroup.bodygroup == bodygroup for bodygroup in bodygroups])))
        bodygroup_count = db.session.query(schema_bodygroup.c.defindex, func.count('*').label("bg_count")).group_by(schema_bodygroup.c.defindex).subquery()
        items_query = items_query.join(bodygroup_count, TF2Item.defindex == bodygroup_count.c.defindex).filter(bodygroup_count.c.bg_count == len(bodygroups))
    return items_query


def format_query(items_query, mod_id, page):
    mod = Mod.query.get_or_404(mod_id)
    authors = set(user.account_id for user in mod.authors)
    if items_query and items_query.count() > 0:
        count = items_query.count()
        items_query = items_query.paginate(int(page), per_page=36)
        for item in items_query.items:
            item.downloads = PackageDownload.query.join(ModPackage).join(TF2Item).filter(TF2Item.defindex == item.defindex) \
                .filter(ModPackage.mod_id == mod_id).filter(~PackageDownload.user_id.in_(authors)).count()
    else:
        return {"err_msg": "No items found matching these criteria.", "count": 0}

    items = render_template('tf2/api_result.html', items=items_query, mod_id=mod_id)
    return {"items": items, "count": count}


@tf2.route('/api/', methods=['POST'])
@login_required
def api():
    form_values = request.form
    item_name = form_values.get("search_data[item_name]")
    classes = form_values.getlist("search_data[classes][]")
    bodygroups = form_values.getlist("search_data[bodygroups][]")
    equip_regions = form_values.getlist("search_data[equip_regions][]")
    mod_id = form_values.get("mod_id")
    page = form_values.get('page')
    if len(classes) < 1:
        return Response(json.dumps({"err_msg": "No classes selected, please select a class to search.", "count": 0}),  mimetype='application/json')
    if not page.isnumeric():
        return Response(json.dumps({"err_msg": "Error, please refresh the page and try again.", "count": 0}),  mimetype='application/json')

    items_query = item_search(classes, bodygroups, equip_regions, item_name)
    items_dict = format_query(items_query, mod_id, page)

    if "err_msg" in items_dict:
        return Response(json.dumps({"err_msg": items_dict.get('err_msg')}),  mimetype='application/json')

    return Response(json.dumps(items_dict),  mimetype='application/json')


@tf2.route('/api/count/', methods=['POST'])
@login_required
def api_count():
    form_values = request.form
    item_name = form_values.get("search_data[item_name]")
    classes = form_values.getlist("search_data[classes][]")
    bodygroups = form_values.getlist("search_data[bodygroups][]")
    equip_regions = form_values.getlist("search_data[equip_regions][]")
    page = request.form.get('page')
    if len(classes) < 1:
        return Response(json.dumps({"err_msg": "No classes selected, please select a class to search.", "count": 0}),  mimetype='application/json')
    if not page.isnumeric():
        return Response(json.dumps({"err_msg": "Error, please refresh the page and try again.", "count": 0}),  mimetype='application/json')

    items_query = item_search(classes, bodygroups, equip_regions, item_name)
    items_dict = {"count": items_query.count()}

    return Response(json.dumps(items_dict),  mimetype='application/json')


@tf2.route('/items/')
def item_download_counts():
    sq = db.session.query(ModPackage.defindex, func.count(PackageDownload).label("download_count"))\
        .join(PackageDownload).group_by(ModPackage.defindex).subquery()
    top_100_downloaded = db.session.query(TF2Item, "download_count").join(sq, TF2Item.defindex == sq.c.defindex)\
        .order_by(desc("download_count")).limit(100).all()
    return render_template('tf2/top_100_downloads.html', items=top_100_downloaded, title="Top {} replaced items".format(len(top_100_downloaded)))

app/templates/construction.html
{% extends "layout.html" %}
{% block content %}
    <div class="center">
        <img src="{{ url_for('static', filename='images/construction.png') }}" />
        <p class="error_description">Please return to <a href="{{ url_for('index') }}">the main page</a>.</p>
    </div>
{% endblock %}

app/templates/credits.html
{% extends "layout.html" %}
{% block content %}
    <b>Additional thanks go to:</b>
    <ul>
        <li><a href="http://facepunch.com/showthread.php?t=1410735" target="_blank">Facepunch, TF2 Mod Emporium</a></li>
        <li>agronholm and other users from the <a href="http://webchat.freenode.net/?channels=sqlalchemy" target="_blank">#sqlalchemy IRC channel on freenode.net</a></li>
        <li>Eimantas Paškonis and fontsquirrel for the <a href="http://www.fontsquirrel.com/fonts/neris" target="_blank">Neris font</a></li>
        <li><a href="https://github.com/wenzhixin" target="_blank">wenzhixin</a> for <a href="https://github.com/wenzhixin/multiple-select" target="_blank">multiple-select</a></li>
    </ul>
{% endblock %}

app/templates/error.html
{% extends "layout.html" %}
{% block content %}
    <div class="center">
        <h1>{{ error.code }}</h1>
        <img src="{{ url_for('static', filename='images/error_{}.png'.format(error.code)) }}" />
        {% if error.quote %}
            <div class="error_quote">{{ error.quote | safe }}</div>
        {% endif %}
        <p class="error_description">{{ error.description | safe }}</p>
    </div>
{% endblock %}

app/templates/header.html
{% from "macros.html" import steam_block %}
<div class="header bg_{{ range(bg_num or config.BG_NUM) | random }} cf">
    <div class="container">
        {%- if current_user.is_authenticated() -%}
            {{ steam_block(current_user, True) }}
            <ul class="dropdown-menu">
                {%- if current_user.is_uploader() -%}
                    <li><a href="{{ url_for('mods.upload') }}">Upload mod<br />(
                        {%- if current_user.upload_credits != -1 -%}
                        {{ current_user.upload_credits | default(0) }} {%- else -%} Infinite {%- endif %} token{{ current_user.upload_credits | pluralize }}
                        )</a></li>
                {%- endif -%}
                {%- if current_user.is_admin() -%}
                    <li><a href="{{ url_for('admin.index') }}">Admin</a></li>
                {%- endif -%}
                {%- if current_user.is_admin() or current_user.is_uploader() -%}
                    <li class="spacer"></li>
                {%- endif -%}
                <li><a href="{{ url_for('users.user_page', user_id=current_user.account_id) }}">Profile</a></li>
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            </ul>
        {%- else -%}
            <a class="steam_login" href="{{ url_for("users.login") }}"><img src="{{ url_for('static', filename='images/sits_large_noborder.png') }}" alt="Sign in with Steam"/></a>
        {%- endif -%}
        <a class="logo" href="{{ url_for('index') }}"></a>
    </div>
</div>

app/templates/index.html
{% extends "layout.html" %}
{%- from 'macros.html' import mod_wall -%}
{% block content %}
    {{ mod_wall(mods) }}
    <div class="button_block">{%- if mods | length > 9 -%}<a href="{{ url_for('mods.all_mods') }}">View more...</a>{%- endif -%}<a href="{{ url_for('tf2.item_download_counts') }}">Top replaced items...</a></div>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{{ title }}{{ " - " if title }}mods.{{ "do" if config.GAME == "dota" else "tf" }}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
    <link rel="icon" sizes="185x185" href="{{ url_for('static', filename='images/favicon_large.png') }}">
    {%- if tag_theme -%}
        {%- set style_name = config.GAME + "_" + tag_theme -%}
    {%- elif config.THEME -%}
        {%- set style_name = config.GAME + "_" + config.THEME -%}
    {%- else -%}
        {%- set style_name = config.GAME -%}
    {%- endif -%}
    {%- block styles -%}
        {% assets style_name + "_css" %}
            <link href="{{ ASSET_URL }}" rel="stylesheet">
        {% endassets %}
    {%- endblock -%}
    {% block scripts %}
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-53670757-1', 'auto');
          ga('send', 'pageview');
        </script>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        {% assets "main_js" %}
            <script src="{{ ASSET_URL }}"></script>
        {% endassets %}
    {% endblock %}
    <meta name="theme-color" content="#312e29">
    <meta name="viewport" content="width=device-width, initial-scale=0.6">
</head>
<body>
    {% include "header.html" %}
    <div class="container cf" id="content">
        {% for category, message in get_flashed_messages(with_categories=true) %}
            <div class="flash alert {{ 'alert-' + category if category != 'message' else 'alert-info'}}">
            <button type="button" class="close">×</button>
                {{message}}
            </div>
        {% endfor %}
        {% block content %}
        {% endblock %}
    </div>
    <footer>
		<div class="container cf">
            <div class="first-line cf">
                <div>Developed by <a target="_blank" href="http://steamcommunity.com/id/smashman2004">Ben 'smash.mn' Williams</a>. Site designed by <a target="_blank" href="http://steamcommunity.com/id/nassimo">Nassim 'NassimO' Sadoun</a>.</div>
                <div>
                    {%- if config.GAME == "tf2" -%}
                    If you like mods.tf, please consider <a target="_blank" href="http://steamcommunity.com/workshop/suggestserviceproviders/?appid=440">recommending us as a service provider on the Workshop</a>.
                    {%- elif config.GAME == "dota" -%}
                    If you like mods.do, please consider <a target="_blank" href="http://steamcommunity.com/workshop/suggestserviceproviders/?appid=570">recommending us as a service provider on the Workshop</a>.
                    {%- endif -%}
                </div>
            </div>
            <div id="valve">Valve, Steam, and Team Fortress are trademarks and/or registered trademarks of <a href="http://valvesoftware.com/" target="_blank">Valve Corporation</a>. mods.{{ "do" if config.GAME == "dota" else "tf" }} is not endorsed by Valve. This site is powered by <a href="http://steampowered.com/" target="_blank">Steam</a>.</div>
            <div class="below-fold cf">
                <div><a href="{{ url_for('additional_credits') }}">Additional credits</a></div>
                <div>Latest change: <a href="http://code.mods.tf/c/{{ config.VERSION }}" target="_blank">{{ config.VERSION }}</a></div>
            </div>
		</div>
	</footer>
</body>
</html>

app/templates/macros.html
{%- macro steam_block(user_info, header=False, no_link=False) -%}
    {%- if not no_link -%}
        <a class="steam_block" href="{{ url_for('users.user_page', user_id=user_info.account_id) }}">
    {%- else -%}
        <div class="steam_block">
    {%- endif -%}
    {%- if user_info.avatar_small -%}
        <div class="iconholder"><img src="{{ user_info.avatar_small }}"/></div>
    {%- endif -%}
    <div class="name">{{ user_info.name }}{{ ' (Moderator)' if header and user_info.is_moderator() }}</div>
    {%- if header -%}
        <div class="dropdown-arrow"></div>
    {%- endif -%}
    {%- if not no_link -%}
        </a>
    {%- else -%}
        </div>
    {%- endif -%}
{%- endmacro -%}
{%- macro form_field(field, placeholder, rows) -%}
    <div class="form-row">
        {{ field.label }}
        <div class="input{{ " select" if field.type == "SelectField" }}{{ " error" if field.errors }}">
            {% if field.description %}
                <div class="description">{{ field.description | safe }}</div>
            {% endif %}
            {{ field(placeholder=placeholder, class="input-default", rows=rows if rows, **kwargs) }}
            {{ field_errors(field) }}
        </div>
    </div>
{%- endmacro -%}
{%- macro field_errors(field) -%}
    {%- if field.errors -%}
        {%- for error in field.errors -%}
            <div class="error">{{ error }}</div>
        {%- endfor -%}
    {%- endif -%}
{%- endmacro -%}
{%- macro pagination(pagination_obj, endpoint, endpoint_values={}) -%}
    {%- if pagination_obj.pages > 1 -%}
        <div class="pagination">
            <ul>
                {%- if pagination_obj.has_prev -%}
                    <li><a class="prev" href="{{ url_for(endpoint, page=pagination_obj.prev_num, **endpoint_values) }}">&#9664;</a></li>
                {%- else -%}
                    <li class="disabled"><a class="prev">&#9664;</a></li>
                {%- endif -%}
                {# Next button #}
                {%- if pagination_obj.has_next -%}
                    <li><a class="next" href="{{ url_for(endpoint, page=pagination_obj.next_num, **endpoint_values) }}">&#9654;</a></li>
                {%- else -%}
                    <li class="disabled"><a class="next">&#9654;</a></li>
                {%- endif -%}
                {# Individual page links #}
                {%- for page in pagination_obj.iter_pages() -%}
                    {%- if page -%}
                        <li class="{{ "active" if pagination_obj.page == page }}"><a class="page" href="{{ url_for(endpoint, page=page, **endpoint_values) }}">{{ page }}</a></li>
                    {%- else -%}
                        <li class="disabled"><a>&hellip;</a></li>
                    {%- endif -%}
                {%- endfor -%}
            </ul>
            {# Number shown on page and total #}
            {%- set first_on_page = (pagination_obj.page - 1)*pagination_obj.per_page + 1 -%}
            {%- set total_on_page = pagination_obj.page*pagination_obj.per_page -%}
            {%- if total_on_page > pagination_obj.total -%}
                {%- set total_on_page = pagination_obj.total -%}
            {%- endif -%}
            <div class="meta">{{ first_on_page }} - {{ total_on_page }} of {{ pagination_obj.total }}</div>
        </div>
    {%- endif -%}
{%- endmacro -%}
{%- macro mod_wall(mods) -%}
{% from 'mods/macros.html' import mod_block %}
    <div class="mod_wall cf">
    {% for mod in mods %}
        {{ mod_block(mod, loop.first) }}
    {% endfor %}
    </div>
{%- endmacro -%}
{%- macro wiki_link(defindex) -%}
    <div class="workshop">
        <a href="http://wiki.teamfortress.com/scripts/itemredirect.php?id={{ defindex }}" target="_blank" title="View on Official Team Fortress Wiki"><img src="{{ url_for('static', filename='images/wiki.png') }}"/></a>
    </div>
{%- endmacro -%}